#!/bin/bash
LOGFILE=encodemp4ize.log
# Concatenate the wget logs and move them to the root
cat flvs/wget-log* > wget.log
rm flvs/wget-log*
mkdir mp4s ogvs webms
echo '' > $LOGFILE
STARTTIME=date
echo "Started at `$STARTTIME`" >> $LOGFILE
# we rsync the flv directory minus the flvs to copy the directory structure
rsync -avz flvs/ webms/ --exclude '*.flv'
rsync -avz flvs/ ogvs/ --exclude '*.flv'
rsync -avz flvs/ mp4s/ --exclude '*.flv'
#find flvs/ -name "*.flv" > flv-files
# The loop
#for f in ./flvs/*
find flvs/ -name "*.flv" | while read f
#while read -r f
do
FILENAME=`echo $f | sed 's#flvs/##'`
#echo $f
#echo $FILENAME
#ffmpeg -i "$f" -n -acodec libvorbis -ac 2 -ab 96k -ar 44100 -b 800k -s 640x360 "./ogvs/`basename $FILENAME .flv`.ogv" < /dev/null
#	echo "$f OGV done" >> $LOGFILE
#ffmpeg -i "$f" -n -acodec libvorbis -ac 2 -ab 96k -ar 44100 -b 800k -s 640x360 "./webms/`basename $FILENAME .flv`.webm" < /dev/null
#	echo "$f WEBM done" >> $LOGFILE
#ffmpeg -i "$f" -n -acodec libfaac -ab 96k -vcodec libx264 -vpre slower -vpre main -level 21 -refs 2 -b 345k -bt 800k -threads 0 -s 640x360 ./mp4s/`basename $f .flv`.mp4 < /dev/null
#ffmpeg -i "$f" -vcodec libx264 -vprofile high -preset slow -b:v 500k -maxrate 500k -bufsize 1000k -threads 0 -acodec libfaac -ab 128k "./mp4s/`basename $FILENAME .flv`.mp4" < /dev/null
MP4FILENAME=`echo $FILENAME | sed 's#\.flv#\.mp4#'`
ffmpeg -i "./$f" -vcodec libx264 -vprofile high -preset slow -b:v 500k -maxrate 500k -bufsize 1000k -threads 0 -acodec libfaac -ab 128k "./mp4s/$MP4FILENAME" < /dev/null
echo "$f MP4 done" >> $LOGFILE
#done < flv-files
done
echo "Started at `$STARTTIME`" >> $LOGFILE
echo "Finished at `date`" >> $LOGFILE
mail -s "Completed encoding of videos on `hostname`" oi.markwilliams@gmail.com < encodemp4ize.log
