#!/bin/bash
if [ $# -eq 1 ]
mkdir flvs
cd flvs
then
  # download each file in the list
  while read -r line; do wget -x -nc "$line"; echo $line >> ../download.log; done < ../flv-lists/$1
fi
mail -s "Download complete on `hostname`" oi.markwilliams@gmail.com < ../download.log
# This is a test
