#!/bin/bash
if [ $# -eq 1 ]
mkdir mp4s
cd mp4s
then
  # download each file in the list
  while read -r line; do wget -x -nc "$line"; echo $line >> ../download.log; done < ../$1
fi
#mail -s "Download complete on `hostname`" m.williams@contentbloom.com < ../download.log
# This is a test
