#!/bin/zsh
MY_DIR=`dirname $0`
source $MY_DIR/nodecount
#Downloaded
echo "Pulling"
echo "-----"

for i in 1 2 5 6
do
  echo vc$i
  ssh ubuntu@vc$i 'cd convert;git pull;'
done
echo vcf
ssh ubuntu@vcf 'cd convert;git pull;'
