#!/bin/zsh
source nodecount
#Downloaded
echo "Pulling"
echo "-----"

for i in `seq 1 $NODECOUNT`
do
  echo vc$i
  ssh ubuntu@vc$i 'cd convert;git pull;'
done
echo vcf
ssh ubuntu@vcf 'cd convert;git pull;'
