#!/bin/zsh
MY_DIR=`dirname $0`
source $MY_DIR/nodecount
#Downloaded
echo "Conversion sizes"
echo "-----"

echo MP4s
for i in `seq 1 $NODECOUNT`
do
  #echo vc$i
  DOWNLOADS=$(ssh ubuntu@vc$i 'du convert/mp4s --max-depth=0')
  echo vc$i = $DOWNLOADS
done
